# azure-disk-storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
  skuname: StandardSSD_LRS  # Use StandardSSD_LRS or Premium_LRS
  kind: Managed
