# values.yaml
app:
  image:
    repository: my-app-image
    tag: latest
  replicas: 3

mysql:
  image:
    repository: mysql
    tag: 5.7
  storage:
    size: 10Gi
    storageClass: azure-disk
  config:
    url: "mysql-service:3306"
    username: "root"
    db: "my_database"
  secret:
    password: QWRtaW5AMTIzMjRj
